### ISSUE TITLE
Customizable password timeout

### ISSUE THREAD

**Issue by drltc** [BitShares/web_wallet#410]
The password timeout requested by the web wallet should be customizable by the user.

After #408 and #409 are implemented, the web wallet will be fairly well-behaved when the password does not exist.

If the password was entered and has timed out, the user should still be able to view his accounts, balances and transactions (but with an icon to warn them that these may be out of date, see #409). However upon trying to perform an action which requires a password, the user should be prompted to enter the password if it has expired.

The user should be able to enter a separate inactivity timeout to flush all private information and lock the wallet, to reduce the possibility that the user's private financial information (such as account names and balances) will be visible to inquisitive passersby with physical access to the console (coworkers, roommates, family members, etc.)  Although in such a situation, the user would obviously be wise to manually lock his workstation and set the OS to lock itself after inactivity.

**Comment by vikramrajkumar** [comment]
Assuming this can be closed.
