### ISSUE TITLE
Prevent similar BITUSD symbol in asset system: B1TUSD  (number 1 , not I )

### ISSUE THREAD

**Issue by btswildpig** [BitShares/web_wallet#451]
I saw the dev just banned the symbol like "BIT"

but B1T is also a easy scam combination .

Imagine B1TUSD  BITUSD  how can you tell if you're not careful ?

Of course , if the current system already ban numbers in the asset symbol , just ignore me ..

**Comment by vikramrajkumar** [comment]
This is unlikely to happen; this is the most planned for now: https://github.com/BitShares/bitshares/issues/1260

**Comment by dnotestein** [comment]
Primary asset names are not allowed to contain digits. Sub-assets are allowed to have digits, but these assets are all under the control of a single entity, so it's not considered a problem.
