### ISSUE TITLE
When changing the wallet passphrase it is not hiding...

### ISSUE THREAD

**Issue by liondani** [BitShares/web_wallet#479]
When using the command   "wallet_change_passphrase <passphrase>"
the password is viewable on the gui and that's not optimal, security wise...
Please hide the password with asterisks and ask for a confirmation input!

I even strongly suggest to give the option to the user to make it from the menu without the need of knowing the command and using it on of the wallet "Console".

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/qt_wallet/issues/96
