### ISSUE TITLE
need double check when sending system assets

### ISSUE THREAD

**Issue by btswildpig** [BitShares/web_wallet#490]
Nowadays , the user issue assets are becoming more popular , people start to send UIAs to socialize with people . But some of them often send out BTS or other valuable assets (BitUSD,BitCNY) by mistake . We need a function to double check when sending out system assets.

It would work like this :  on the "confirm transfer" pop up window , add a check box and hint , people need to "check" the check box in order to send system assets .  

The hint should like this : You are transferring system assets like BTS,BitUSD instead of user issue assets . Do you really want to continue ? 

Additional solution : When users go to the account page , do not display the symbol BTS by default , the symbol name should be blank by default , user need to choose a specific symbol to send , every time a transaction is done , the symbol name need to clear again .

**Comment by vikramrajkumar** [comment]
Assuming sufficiently addressed by: https://github.com/BitShares/web_wallet/commit/87445b29a414d136fe7ace451f2fdb2d0f545dd8
