### ISSUE TITLE
Show account address as well as account key

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/web_wallet#514]
The GUI shows account key, but you should be able to access the address for your account somewhere in the GUI as well.

**Comment by valzav** [comment]
For what a regular user may need account address?

**Comment by valzav** [comment]
Is there a way to stick to either addresses or to account keys? I'm thinking about better UX and having addresses alongs with public keys may confuse users.

**Comment by jcalfee** [comment]
We have account names for convenience already, so I'm thinking the public key is the most flexible info for anything that may come up in the future (as that can be converted to the other formats).  Thanks to @theoreticalbts and https://github.com/BitShares/bitshares/issues/1204, we have `wallet_transfer_to_address` accepting public keys...  So, I don't have any reason to keep this ticket open.

**Comment by dnotestein** [comment]
Well, I think we need to settle the issue of addresses versus account keys, it's a serious source of confusion I think. Let's discuss it on Monday.

**Comment by vikramrajkumar** [comment]
I believe it was decided that we will not expose addresses to users.
