### ISSUE TITLE
Toggle Favorite button is buggy [GUI]

### ISSUE THREAD

**Issue by growler17** [BitShares/web_wallet#516]
The star icon is not updating as it should when clicked. If you click the icon, leave the page, wait ~20 seconds then return, sometimes the star icon will be updated to reflect the change, however this method does not work 100% of the time.

Issue appears to affect all user profile pages. Specifically, I was able to reproduce this issue for users Growler, andrethegiant, and drewcifer.

client version v.0.4.27.2
build win32 64-bit
OS: Windows 8.1

**Comment by vikramrajkumar** [comment]
Too old.
