### ISSUE TITLE
0.5.1 still saying "Symbol name should be 3-8  uppercase ..." on asset creation page

### ISSUE THREAD

**Issue by btswildpig** [BitShares/web_wallet#528]
The asset name can be longer than 8 now , so the hint is wrong . 
Both wrong in Chinese and English language . 

![image](https://cloud.githubusercontent.com/assets/9744912/5813748/95d1dede-a0bd-11e4-91ac-13acccea4fac.png)

**Comment by vikramrajkumar** [comment]
details: https://github.com/BitShares/bitshares/issues/1181
