### ISSUE TITLE
Price limited shorts incorrectly placed into short wall

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/web_wallet#530]
Shorts with a price limit need to be excluded from the short wall and listed as separate orders, if the limit is effective at the current feed price.

**Comment by theoreticalbts** [comment]
See:  https://bitsharestalk.org/index.php?topic=13499

**Comment by dnotestein** [comment]
This was fixed yesterday: https://github.com/BitShares/web_wallet/commit/1867aee0d2e089da4f314625731db9808e628c3e

**Comment by valzav** [comment]
yesterday I've fixed short's total amount, I didn't change the condition whether it gets into the short wall or not. 
currently the condition is like below:
    is_in_short_wall: (short, shorts_price, inverted) ->
        return true if !short.short_price_limit or short.short_price_limit == 0.0
        return (not inverted and short.short_price_limit > shorts_price) or (inverted and short.short_price_limit < shorts_price)

please let me know if you see any flows in it

**Comment by vikramrajkumar** [comment]
@theoreticalbts can probably check the above condition.

**Comment by theoreticalbts** [comment]
It looks right.  I don't have a strong opinion whether shorts that exactly match the feed price should be included in the wall or not (the code looks like it will separate them).

Sorry I filed the ticket when the issue was already fixed, I updated to 0.5.1 but it turns out my browser was caching the previous version.  0.5.1 has correct behavior, so closing the ticket.
