### ISSUE TITLE
BTS Max supply displays 10billion , it should display the real max supply 

### ISSUE THREAD

**Issue by btswildpig** [BitShares/web_wallet#548]
![image](https://cloud.githubusercontent.com/assets/9744912/5936140/af054714-a71c-11e4-9297-f352c19e9591.png)

BTS Max supply displays 10billion , it should display the real max supply to avoid negative comments that BTS can up to 10billion under current system .

**Comment by btswildpig** [comment]
It's hurting the promotion , please fix it asap .

**Comment by svk31** [comment]
I actually removed BTS from the list of market assets with commit #561 , it didn't really belong there. This means you can't access BTS anymore to get that screen. Unless you really want it somewhere we can probably close this. Maybe we can put BTS total supply somewhere though?

**Comment by valzav** [comment]
I think we can close this issue
