### ISSUE TITLE
Confusing Text When Registering

### ISSUE THREAD

**Issue by dclark25** [BitShares/web_wallet#549]
As a new user, it was slightly confusing when I was trying to register and it said the transaction fee would be 0.5 BTS where as I have 0 BTS in my account, yet I was still able to register anyway.

**Comment by theoreticalbts** [comment]
There's a dropdown to select a faucet, but I think there should be a line after "Transaction fee:  0.5 BTS" which says "If you don't have any BTS yet, you can select a faucet to pay this fee for you."

**Comment by valzav** [comment]
Will do that

**Comment by valzav** [comment]
done
