### ISSUE TITLE
Error/alert "Show Details" not working

### ISSUE THREAD

**Issue by vikramrajkumar** [BitShares/web_wallet#554]
https://github.com/BitShares/bitshares/issues/1333

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/web_wallet/commit/e56a0b86388b4704cdc7f13189c7058c789d7319

**Comment by vikramrajkumar** [comment]
Apparently still broken: https://github.com/BitShares/bitshares/issues/1364

**Comment by valzav** [comment]
this should be fixed by this commit https://github.com/BitShares/web_wallet/commit/e56a0b86388b4704cdc7f13189c7058c789d7319
but it didn't get into released version
