### ISSUE TITLE
Add send to address support in GUI

### ISSUE THREAD

**Issue by wildbunny** [BitShares/web_wallet#558]
Add support for sending to a bitshares address to the 'Transfer' tab inside the account section of the wallet.

This will allow merchants and exchanges to generate a unique BTS deposit address for each user, thereby circumventing scam accounts with similar names to genuine accounts, e.g bter.

**Comment by valzav** [comment]
We are trying to avoid to use addresses on a GUI level. Exchanges can use memo field.
Regarding scam accounts - we added a warning to transfer page, also we have robohashes and also there is address book, so users can add frequently used account names to address book and be more safe sending to repeating names.
