### ISSUE TITLE
Need to add base asset symbol parameter in calls: blockchain_market_list_*

### ISSUE THREAD

**Issue by jcalfee** [BitShares/web_wallet#564]
The web wallet runs this command:
`blockchain_market_list_shorts USD 1000`

The second parameter is actually the base symbol and the 3rd parameter is the limit.  It is throwing an assertion error.

**Comment by svk31** [comment]
I'd change it but there's this at the top of the file: 

> # Warning: this is a generated file, any changes made here will be overwritten by the build process

How is this actually generated?

**Comment by valzav** [comment]
You need to use this https://github.com/BitShares/bitshares/tree/master/libraries/api/ruby_generator

**Comment by valzav** [comment]
Hmm.. what I see is blockchain_market_list_shorts accepts only 2 parameters, not 3:

blockchain_market_list_shorts <quote_symbol> [limit]                                                  Returns the short side of the order book for a given market
Returns the short side of the order book for a given market

Parameters:
  quote_symbol (asset_symbol, required): the symbol name the market is quoted in
  limit (uint32_t, optional, defaults to "-1"): the maximum number of items to return, -1 for all

**Comment by svk31** [comment]
Yea you're right actually, just checked and even in DVS 0.6.3 it's like that. I'm also using it like that in the bitsharesblocks back-end (with only asset symbol as parameter)

**Comment by valzav** [comment]
@jcalfee, should we close this issue?
