### ISSUE TITLE
Max memo size should be extended in the GUI as well 

### ISSUE THREAD

**Issue by btswildpig** [BitShares/web_wallet#566]
GUI is Still at 19 bytes while console can be 51 bytes limit

**Comment by svk31** [comment]
The max memo size is currently being read from the client, so as long as blockchain_get_info is reporting memo_size_max: 19 then the GUI will use that. 

@vikramrajkumar should get_info be reporting a different value? It's at 19 even in DVS v0.6.3

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/bitshares/commit/350250c4dc3582742e8602bd8a4f61b98d739630
