### ISSUE TITLE
newlayout DVS 0.6.3 chinese community feedback

### ISSUE THREAD

**Issue by vikramrajkumar** [BitShares/web_wallet#567]
https://bitsharestalk.org/index.php?topic=13998.msg182257#msg182257

**Comment by svk31** [comment]
I went through some of those and fixed a couple, but some aren't actual bugs: 

3: The client already does that, at least on my end
5: Fixed
8: Fixed by yourself in backend
9: Simply due to using DVS
10: Fixed

**Comment by valzav** [comment]
#1 Fixed
#2 Probably this needs to be checked on the toolkit's side
#3 I think this was because of missing tranlation
#4 Created separate issue for this - #577
#5 Fixed by svk
#6 Hope this is fixed by #5 
#7 Needs more research (not critical)
#8 Fixed (hardcoded)
#9 -
#10 Fixed
