### ISSUE TITLE
Menus are broken in Korean Windows

### ISSUE THREAD

**Issue by clayop** [BitShares/web_wallet#585]
http://i.imgur.com/OxerRRc.png

I've tried other languages, but they all show "ko" only.

**Comment by svk31** [comment]
For me in Windows they all work except Korean which just falls back to English, while in Ubuntu and using Chrome Korean works fine.. QT engine issue maybe?

**Comment by clayop** [comment]
Maybe due to the empty fields. So Cryptfun(sean0010) made pull requests on Korean translation. We'll see this helps.

**Comment by vikramrajkumar** [comment]
Same thing as @svk31 on 0.6.0 Mac. A build with the latest now works correctly.

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/qt_wallet/commit/16ce91d5e219b3570eecf8fd481e91fa87d90267
