### ISSUE TITLE
0.6.0 Top Account menu issue -

### ISSUE THREAD

**Issue by cassiopaia** [BitShares/web_wallet#592]
Last choosen acc isn't displayed sometimes after swtiching to another acc ... have to switch to different accounts several times before this account is displayed again top right acc nav !

**Comment by valzav** [comment]
Probably this is not a bug but feature - I don't display current account in the list, instead you can click on Account Details

**Comment by cassiopaia** [comment]
sure if it works like that ! But e.g i'm on cass1 and then swtich to cass2! But if i'm looking on dropdown then, sometimes cass1 isn't listed even though current account is cass2

**Comment by valzav** [comment]
no, you should see your cass1 account when you switched to cass2, I'll be watching this, hope it reproducible in my dev environment.

**Comment by vikramrajkumar** [comment]
Another report: https://bitsharestalk.org/index.php?topic=14155.msg185242#msg185242
