### ISSUE TITLE
Transaction fees computed wrong in GUI for assets, causing inability to send transfer

### ISSUE THREAD

**Issue by vikramrajkumar** [BitShares/web_wallet#600]
https://github.com/BitShares/qt_wallet/issues/104

**Comment by valzav** [comment]
@jcalfee could you take a look at this?

**Comment by jcalfee** [comment]
Yes

**Comment by jcalfee** [comment]
Here is a review: The wallet will query wallet_get_transaction_fee <desired asset> where the desired asset is the asset being transferred. The asset that is returned by the RPC command is the asset that is shown in the GUI as the fee.

If there is not enough to pay in that asset, the bitshares_client will go looking for other assets that can pay the fee. How will the wallet know what fee to display to the user before they confirm the transfer?

Also: If the asset being transferred has a balance in any market pegged asset that has enough active price feeds, that would probably be a good fee to return and to accept. It may be an option for Dan to get price feeds published for TRADE.BTC to make it easier to transfer.
