### ISSUE TITLE
GUI does not use translated files

### ISSUE THREAD

**Issue by jimewu** [BitShares/web_wallet#603]
I know the market rule is translated here:
https://github.com/BitShares/web_wallet/blob/b836a2aecde807eac58f45f3e823ce695e0d09e6/app/templates/context_help/zh-CN/market.html

but when I set my UI to zh-CN, the help file still show the EN file:
http://i.imgur.com/slqeTks.png

**Comment by valzav** [comment]
@svk31 oh great - I think you now can commit directly to the web_wallet repo

**Comment by svk31** [comment]
yep BM added me the other day :)
