### ISSUE TITLE
on the Delegates page - typing in the filter should show both top delegates and stand by delegates

### ISSUE THREAD

**Issue by valzav** [BitShares/web_wallet#609]

**Comment by svk31** [comment]
I can see your point but I'm not sure I agree, the problem with having standby and active delegates on the same page is much worse performance on loading the page. I've made a commit that moves the filter box inside the tab to make it more explicit that it applies only to the currently shown delegates. If you don't find the delegate you're looking for it should be logical to look in the standby tab imo.
