### ISSUE TITLE
not all accounts showing up 0.6.1

### ISSUE THREAD

**Issue by vikramrajkumar** [BitShares/web_wallet#611]
https://bitsharestalk.org/index.php?topic=14190.msg184789#msg184789

**Comment by jcalfee** [comment]
@valzav I could not reliably reproduce, but I suggest this small change this could very well fix this.  It is safe.  It means that if a request comes for an account list it will execute and update objects angularjs is monitoring (on the next block):
```
     observer_config:->
         name: "WalletEachBlockObserver"
         frequency: "each_block"
@@ -49,7 +63,8 @@ class Wallet
 #            @refresh_balances_promise = null
 #            @transactions_loading_promise = null
 #            @check_vote_proportion_promise = null
-#            @refresh_accounts_promise = null
+            if @refresh_accounts_request
+                @refresh_accounts_promise = null
             @refresh_accounts()
             deferred.resolve(true)
         #notify: (data) ->
```

**Comment by valzav** [comment]
@jcalfee, probably you are right, I'll do some more research on this
