### ISSUE TITLE
Incorrect decimal places for some BitAssets in /markets

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/web_wallet#627]
Specifically, the "total" field is 10x too large for BitGold shorts in version 0.6.1.

I suspect the problem is in setting of `order.cost` which occurs [here](https://github.com/BitShares/web_wallet/blob/a4798209779ab9923608209fd69fac088bbd0b53/app/js/controllers/market.coffee#L196-L215).  This is web_wallet commit 3044b4fdd9c59960de81c18950011375b4f6143f

**Comment by valzav** [comment]
@theoreticalbts could tell me where do you see this issue? Featured Markets charts?

**Comment by cassiopaia** [comment]
thx
