### ISSUE TITLE
Decimal erroer Exchange Dashboard open orders

### ISSUE THREAD

**Issue by cassiopaia** [BitShares/web_wallet#631]
I begin to think on exchange dashboard page in GUI there is an error with decimals!
Total on my side to pay are 416.153 and 223.132

but GUI shows 
![bildschirmfoto 2015-02-26 um 12 04 18](https://cloud.githubusercontent.com/assets/6280810/6390828/f4aa4b94-bdaf-11e4-91d9-05a143429e17.png)

or did i get something wrong?

**Comment by vikramrajkumar** [comment]
Duplicate #627 ?

**Comment by robrigo** [comment]
I see the same decimal issue on margin orders under Open Orders. 

I am also seeing an incorrect price and incorrect total for an open short in this list. The collateral value is correct though.

**Comment by valzav** [comment]
this should be fixed in the latest gui update - 0.6.2-a
