### ISSUE TITLE
disable GUI during initial sync

### ISSUE THREAD

**Issue by vikramrajkumar** [BitShares/web_wallet#633]
It is considered unsafe for a user to perform any transaction while syncing, and info on the state of the blockchain while syncing is fairly useless.

There has been a consistent stream of tech support requests from confused new users who get errors as a result of trying to use the software while syncing.

**Comment by valzav** [comment]
This is on my to do list already. The plan is to make user to create account and register it via the faucet and entertain/educate user showing some slides.

**Comment by vikramrajkumar** [comment]
Related: #406

**Comment by vikramrajkumar** [comment]
Assuming addressed by: https://github.com/BitShares/web_wallet/commit/e0b76d5544c91280c39a5934199a44d29255e845
