### ISSUE TITLE
API changes for 0.9.x

### ISSUE THREAD

**Issue by vikramrajkumar** [BitShares/web_wallet#637]
@valzav @jcalfee @grzegorzs

Accounts, contacts, and approvals are now 3 completely different types of records in the wallet backend. Previously they were all considered "accounts".

Modified:
- `wallet_account_create` - just doesnt accept extra private data on creation
- `wallet_transfer` -- now accepts contacts, public keys, addresses as the recipient in addition to account names
- some of the fields in any `wallet_account_record` were removed:
  - `is_my_account`
  - `approved`
  - `is_favorite`

Removed:
- `wallet_get_name`
- `wallet_account_set_favorite`
- `wallet_account_set_approval`
- `wallet_add_contact_account`
- `wallet_transfer_to_legacy_address`
- `wallet_transfer_to_address`
- `wallet_transfer_to_public_account`
- `wallet_transfer_from`
- `wallet_account_update_private_data`
- `wallet_list_favorite_accounts`
- `wallet_list_unregistered_accounts`
- `wallet_list_my_accounts`
- `wallet_get_account_public_address`
- `wallet_remove_contact_account`
- `wallet_check_vote_status`

Added:
- `wallet_list_contacts`
- `wallet_get_contact`
- `wallet_add_contact`
- `wallet_remove_contact`
- `wallet_list_approvals`
- `wallet_get_approval`
- `wallet_approve`
- `wallet_set_custom_data`

**Comment by vikramrajkumar** [comment]
@dnotestein @emfrias I guess this is prob relevant to BlockTrades as well.

**Comment by dnotestein** [comment]
ok, this isn't in current release, yet, correct? It sounds like these are changes for 0.7.0. Thanks for the heads up, though.

**Comment by vikramrajkumar** [comment]
right 0.7.0

**Comment by grzegorzs** [comment]
```
wallet_add_contact <contact> [label]
  label (string, optional, defaults to ""): an optional custom label to use when referring to this contact
```
Is the target "custom label" can be used for example as a recipient in wallet_transfer?

**Comment by vikramrajkumar** [comment]
Yes that is the intent. It should work in `wallet_transfer` as the recipient if you prefix the label string with `label:`

**Comment by vikramrajkumar** [comment]
@valzav @jcalfee

Removed:
- `blockchain_is_synced`
  - To replicate: `blockchain_is_synced == true` when current head block age is less than num delegates times block interval = 1010 seconds
- `blockchain_get_security_state`
  - green: participation > 80
  - yellow: participation > 60 
  - grey: not synced
  - red: otherwise

**Comment by valzav** [comment]
What are the wallet's accounts? I mean the list returned by wallet_list_accounts.
I notices that it lists an account that doesn't belong to me but the one I used to send to.

**Comment by vikramrajkumar** [comment]
It should only return any local accounts (both registered and unregistered) that you control any keys for. When the release is made, there will be one-time upgrade logic that deletes any contact accounts from that list in existing wallets.

**Comment by vikramrajkumar** [comment]
@valzav @jcalfee @grzegorzs @emfrias @dnotestein @nmushegian @theoreticalbts @pmconrad @robrigo

Removed:
- `wallet_asset_create`
- `wallet_asset_update`
- `wallet_asset_issue`
- `wallet_asset_issue_to_addresses`
- `wallet_asset_authorize_key`

Added:
- `wallet_mia_create`
- `wallet_uia_create`
- `wallet_uia_issue`
- `wallet_uia_issue_to_addresses`
- `wallet_uia_collect_fees`
- `wallet_uia_update_description`
- `wallet_uia_update_supply`
- `wallet_uia_update_fees`
- `wallet_uia_update_active_flags`
- `wallet_uia_update_authority_permissions`
- `wallet_uia_update_whitelist`

**Comment by vikramrajkumar** [comment]
Also pinging: @svk31

**Comment by valzav** [comment]
Was the transactions object changed? I don't see withdraws and depositions fields anymore..

**Comment by vikramrajkumar** [comment]
@valzav @jcalfee @svk31 Yes blockchain `transaction_record` format was also changed:

Old: https://github.com/BitShares/bitshares/blob/5221fc5a64f0afb06de3990a8294e108edbf2c45/libraries/blockchain/include/bts/blockchain/transaction_evaluation_state.hpp#L70-L102
New: https://github.com/BitShares/bitshares/blob/47cf4074a8c94ed8f0b52e036a7c0211681e29d4/libraries/blockchain/include/bts/blockchain/transaction_evaluation_state.hpp#L49-L62

**Comment by vikramrajkumar** [comment]
Also pinging: @wildbunny

**Comment by wildbunny** [comment]
These are upcoming changes for 0.8.0? Did the json returned by wallet_get_transaction also change?

**Comment by vikramrajkumar** [comment]
Yes they will first go in the next devshares release 0.8. `wallet_get_transaction` output should not have changed.

**Comment by grzegorzs** [comment]
@vikramrajkumar
How use (in tests) `wallet_asset_issue_to_addresses`?

**Comment by vikramrajkumar** [comment]
@valzav @jcalfee @svk31 

Market history output now separates `volume` into `base_volume` and `quote_volume` (#1471). I think the only command that is effected is `blockchain_market_price_history` but not totally sure.

**Comment by svk31** [comment]
@vikramrajkumar blockchain_market_price_history is currently the principal reason why the market pages feel sluggish, as it is very slow to return results no matter the amount of data you're requesting. This is also an issue for bitsharesblocks and is the reason why I'm only displaying ASSET / BTS markets atm, fetching non-BTS base asset data would completely overwhelm my server. Unless some of the changes you've already made have improved the performance, would it be possible to have a look at that?

**Comment by vikramrajkumar** [comment]
@svk31 Yeah I'll take a look: https://github.com/BitShares/bitshares/issues/1202

**Comment by abitmore** [comment]
> @vikramrajkumar blockchain_market_price_history is currently the principal reason why the market pages feel sluggish, as it is very slow to return results no matter the amount of data you're requesting. This is also an issue for bitsharesblocks and is the reason why I'm only displaying ASSET / BTS markets atm, fetching non-BTS base asset data would completely overwhelm my server. Unless some of the changes you've already made have improved the performance, would it be possible to have a look at that?

@svk31 @vikramrajkumar @bytemaster 
We're using a structure`std::map<market_history_key(quote_id, base_id, granularity, start_time), value>` to store market_price_history data, maybe it's the reason why the `blockchain_market_price_history` API is slow? It's said that iterating over large `std::map` object is slow (in compare with `std:vector`). 
Will it help if we change it to somewhat like this structure: `std::map<market_history_key(quote_id, base_id, granularity), std::vector<pair<start_time, value>>>`? In this way iterating will be much faster, looking up will be not slower if use a binary search algorithm inside the vector, and the cost for storing new data is almost constant.

**Comment by abitmore** [comment]
> @vikramrajkumar blockchain_market_price_history is currently the principal reason why the market pages feel sluggish, as it is very slow to return results no matter the amount of data you're requesting. This is also an issue for bitsharesblocks and is the reason why I'm only displaying ASSET / BTS markets atm, fetching non-BTS base asset data would completely overwhelm my server. Unless some of the changes you've already made have improved the performance, would it be possible to have a look at that?

@svk31 After some research, I think you mean `blockchain_market_order_history`? Since currently there is no data with non-BTS pairs in `blockchain_market_price_history`, it wouldn't be an issue by now. We will have data of non-BTS pairs in the new version, you may like to take a look then.
See https://github.com/BitShares/bitshares/issues/1202#issuecomment-93776516

**Comment by vikramrajkumar** [comment]
All `mail_` and `wallet_mail_` commands have been removed.
