### ISSUE TITLE
Reload on Transfer tab, errors with "Insufficient balances"

### ISSUE THREAD

**Issue by Xeldal** [BitShares/web_wallet#644]
Upon entering the transfer tab, often for about 5 to 10 seconds it displays "Insufficient balances" in the Amount field.  

If you right click>Reload the page.  The Amount field stays "Insufficient balances"  indefinitely, and prevents you fund using it.

**Comment by valzav** [comment]
Reload is the last resort - it brakes natural single page app execution flow, I don't recommend to use just to speed up data transfer from the rpc server to client.
Nonetheless I've tried to fix this particular issue, see the commit above.

**Comment by Xeldal** [comment]
I don't know if its related by now I can not transfer to a name with with a " . "  (dot)  in it.  
When I type the dot the box turns red and I cannot send.   Even saved 'Address Book' names with a dot in them do not work

I didn't have this issue until after I refresh'd the transfer page at some point.  
Restarting the client doesn't fix it.

win7x64 0.6.2

**Comment by valzav** [comment]
@Xeldal this is fix in 0.6.2-b GUI update, just select check for the updates in the menu. (note, this may not work with custom built client)
