### ISSUE TITLE
Unable to Send to account with a "." in it.

### ISSUE THREAD

**Issue by bytemaster** [BitShares/web_wallet#647]
win7x64 v0.6.2

I'm unable to send to any name with a dot in it.  Once I enter the dot the box turns red and no matter what I type next it stays red and cannot send anything.

This is a new wallet and a new account, same machine different data-dir.   At least the transaction History works on this one.   :  (

**Comment by valzav** [comment]
This is fixed in 0.6.2-b GUI update

**Comment by valzav** [comment]
Please close this issue if 0.6.2-b GUI update works for you, let me know you are not able to update it or it doesn't fix the issue.

**Comment by vikramrajkumar** [comment]
The OP was from: https://bitsharestalk.org/index.php?topic=14545.msg191206#msg191206

**Comment by vikramrajkumar** [comment]
https://bitsharestalk.org/index.php?topic=14545.msg191224#msg191224

**Comment by vikramrajkumar** [comment]
Duplicate: #639
