### ISSUE TITLE
Indicate when you are transferring to another one of your accounts.

### ISSUE THREAD

**Issue by bytemaster** [BitShares/web_wallet#648]
All of "my accounts" should be "in the addressbook" by default.   Also if I have the keys to that account then it should be indicated via something like 'your account'  under the icon / text.   This will help people feel much more comfortable when transferring to themselves.

**Comment by jcalfee** [comment]
I like this a lot.. In the online wallet we don't have a stateful address book (not deterministic or on chain).  I do however set the "is_my_account" boolean (just like the native client) when fetching an account..  If that could be used it would avoid a dependency on the address book.

**Comment by valzav** [comment]
I'm adding newly created accounts to address book but accounts you've created before address book was implemented didn't get into it.

**Comment by vikramrajkumar** [comment]
@jcalfee Please note that the `is_my_account` flag has been removed in the latest code: #637

**Comment by vikramrajkumar** [comment]
> I'm adding newly created accounts to address book but accounts you've created before address book was implemented didn't get into it.

@valzav Just a suggestion: you might want to consider adding some one-time upgrade code. I do this in the backend based on `wallet_get_info["version"]` which is getting bumped from 109 to 110 for 0.7.x (see: https://github.com/BitShares/bitshares/issues/1418). You could also maintain your own custom version info for the GUI and do any upgrades based on that.
