### ISSUE TITLE
 It is not possible to choose "vote_none" from the gui when we make transfers

### ISSUE THREAD

**Issue by liondani** [bitshares/web_wallet#655]
...only if you just use the "vote" option but not when you transfer funds... by default it "votes-all" on transfers

**Comment by xeroc** [comment]
... furthermore, the default behavior of the CLI is vote_recommanded

**Comment by liondani** [comment]
yep you are right, but I can not choose another option except the default when transferring funds.
It should be not be a big problem since if want to vote we have all the options there,but the problem in my case was that I would make a succesfull transfer only if I had the option to "vote_none" due a current temporary bug... see the issue I oppened #656

**Comment by abitmore** [comment]
If I remember, In GUI, the vote setting could be changed in the 'advanced' page.
