### ISSUE TITLE
Transfers not possible when to many delegates are approved from the wallet/account

### ISSUE THREAD

**Issue by liondani** [BitShares/web_wallet#656]
I managed to make a transfer only from console with the parameter "vote_none"  !

error I get :

10 assert_exception: Assert Exception
record.slate.size() <= BTS_BLOCKCHAIN_MAX_SLATE_SIZE: 
    {}
    bitshares  wallet.cpp:956 get_delegate_slate

    {"transaction":{"expiration":"2015-03-17T13:05:48","reserved":null,"operations":[{"type":"deposit_op_type","data":{"amount":100000,"condition":{"asset_id":0,"slate_id":0,"type":"withdraw_signature_type","data":{"owner":"BTSB8k2PUxhsrTUchwuv3anV1FbRJmtyTRzt","memo":{"one_time_key":"BTS8fdLXvPoU9Gqzf3tG2AoYkozdzaEqQ8xFX3WJobpu5wQJFTGrc","encrypted_memo_data":"1dd5760de29299599744ebc6a0db8384a26d00e8c61d165e5e7d7c8bd43b7491cb5eeef984aff776ce6888593d58c949ae8032e55bf750ee9bc39498fba42dbf"}}}}},{"type":"withdraw_op_type","data":{"balance_id":"BTS4Ac5PfDwpSFqwEmj6w75YVH1imbKJu6wr","amount":110000,"claim_input_data":""}}],"signatures":[]},"strategy":"vote_recommended"}
    bitshares  wallet.cpp:800 set_delegate_slate

    {"trx":{"expiration":"2015-03-17T13:05:48","reserved":null,"operations":[{"type":"deposit_op_type","data":{"amount":100000,"condition":{"asset_id":0,"slate_id":0,"type":"withdraw_signature_type","data":{"owner":"BTSB8k2PUxhsrTUchwuv3anV1FbRJmtyTRzt","memo":{"one_time_key":"BTS8fdLXvPoU9Gqzf3tG2AoYkozdzaEqQ8xFX3WJobpu5wQJFTGrc","encrypted_memo_data":"1dd5760de29299599744ebc6a0db8384a26d00e8c61d165e5e7d7c8bd43b7491cb5eeef984aff776ce6888593d58c949ae8032e55bf750ee9bc39498fba42dbf"}}}}},{"type":"withdraw_op_type","data":{"balance_id":"BTS4Ac5PfDwpSFqwEmj6w75YVH1imbKJu6wr","amount":110000,"claim_input_data":""}}],"signatures":[]}}
    bitshares  transaction_builder.cpp:794 finalize

    {}
    bitshares  common_api_client.cpp:3966 wallet_transfer

    {"command":"wallet_transfer"}
    bitshares  cli.cpp:626 execute_command

**Comment by xeroc** [comment]
From 
https://github.com/BitShares/bitshares/blob/master/libraries/blockchain/include/bts/blockchain/config.hpp#L28
I can see that you are only allowed to vote for 111 delegates .. if your slate is bigger you cannot construct the transaction ..

How many delegates do you have approved?

**Comment by vikramrajkumar** [comment]
Moved: https://github.com/BitShares/bitshares/issues/1452
