### ISSUE TITLE
can't display the help file  on  market page

### ISSUE THREAD

**Issue by todasun** [BitShares/web_wallet#660]
![default](https://cloud.githubusercontent.com/assets/10720816/6722735/956b2b24-ce19-11e4-99b8-b5c361fdde2a.png)
can't display the help file

**Comment by valzav** [comment]
What version is this? We've changed how this page works in late 0.6.x so it not longer looks for market.html

**Comment by todasun** [comment]
v0.8.0 still can't display

**Comment by todasun** [comment]
I see,because i use total chain.7z provided of some guy
when I delete the chain & sync Start all over again  it displays
