### ISSUE TITLE
Selected Currency type gets wiped periodically

### ISSUE THREAD

**Issue by dnotestein** [BitShares/web_wallet#662]
While doing a transfer, I select the currency type as BTS, for example. Then after waiting about a few seconds, it gets reset to "Select Currency" if I don't complete the transfer info and send it relatively quickly (my guess is it's being cleared when a new block comes in).

**Comment by valzav** [comment]
Fixed in 0.8.0 https://github.com/BitShares/web_wallet/commit/aaecff29c7965460b18454713a487dc47bae3cf8
