### ISSUE TITLE
I0709 13:38:41.562055    2494 chain_manager.go:782] Bad block #829744 (6c9fc7a652d6bcc608ec40c0deee95529e7006891af4973ade254749f703d481) I0709 13:38:41.562341    2494 chain_manager.go:783] invalid receipt root hash. received=be9843b1b4867d2e24f92be16005c8d692cd0b2b4a924037996f166daf04961f calculated=a37d0d92dcd8ffb93919254980975b7f22fc1017b3bbe5b6880c164af618807c

### ISSUE THREAD

**Issue by pureland** [BitShares/web_wallet#697]
I0709 13:38:41.562055    2494 chain_manager.go:782] Bad block #829744 (6c9fc7a652d6bcc608ec40c0deee95529e7006891af4973ade254749f703d481)
I0709 13:38:41.562341    2494 chain_manager.go:783] invalid receipt root hash. received=be9843b1b4867d2e24f92be16005c8d692cd0b2b4a924037996f166daf04961f calculated=a37d0d92dcd8ffb93919254980975b7f22fc1017b3bbe5b6880c164af618807c

**Comment by vikramrajkumar** [comment]
Wrong project.
